print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/mint/Development/Games/ld30/Assets/Models/display.mb"`)
{		
	file -o "/Users/mint/Development/Games/ld30/Assets/Models/display.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/mint/Development/Games/ld30/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/mint/Development/Games/ld30/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/mint/Development/Games/ld30/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
